### PR TITLE
modify interfaces cdotc,zdotc,cdotu,zdotu to support openblas

### LINKED ISSUE #1643: New EXX implementation not working with gcc+openmpi+openblas
### Describe the bug

1. When running with more than one mpi process, the program would get stuck after initialization.
2. When running with single mpi process, the program sometimes produces wrong results. i.e. with the hse example in the example folder, when changing the number of k points in KPT file to 111, Gamma_only=0 and Gamma_only=1 would give different results.

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

gcc-11, openmpi, openblas

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by maki49**
fix [abacus issue 1643](https://github.com/deepmodeling/abacus-develop/issues/1643) along with [abacus PR 2193](https://github.com/deepmodeling/abacus-develop/pull/2193)

### CODE REVIEW

File: include/RI/global/Blas-Fortran.h [hunk 1]
```diff
@@ -28,15 +28,24 @@ extern "C"
 	float sdot_(const int*const n, const float*const X, const int*const incX, const float*const Y, const int*const incY);
 	double ddot_(const int*const n, const double*const X, const int*const incX, const double*const Y, const int*const incY);
 
+#ifdef __MKL
 	// d = Vx * Vy
 	//	reason for passing results as argument instead of returning it:
 	//	https://www.numbercrunch.de/blog/2014/07/lost-in-translation/
-	void cdotu_(std::complex<float>*const result, const int*const n, const std::complex<float>*const X, const int*const incX, const std::complex<float>*const Y, const int*const incY);
+	void cdotu_(std::complex<float>* const result, const int* const n, const std::complex<float>* const X, const int* const incX, const std::complex<float>* const Y, const int* const incY);
```
Comment (caic99) [inline include/RI/global/Blas-Fortran.h]: @maki49 But MKL has its own C interface for BLAS, putting return value at the end of function parameters. I wonder if it will cause difference.
https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-c/2023-1/cblas-dotc.html

Comment (maki49) [reply include/RI/global/Blas-Fortran.h]: > @maki49 But MKL has its own C interface for BLAS, putting return value at the end of function parameters. I wonder if it will cause difference. https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-c/2023-1/cblas-dotc.html

I think both the two ways are okay: one is `cdotc( &result, n, x, 1, y, 1)`, the other is `cblas_cdotc( n, x, 1, y, 1, &result )`.
https://www.intel.com/content/www/us/en/docs/onemkl/developer-guide-macos/2023-0/call-blas-funcs-return-complex-values-in-c-code.html

**Comment by maki49** [comment]
@PeizeLin did some tests: compiling OpenBLAS with ifort and gfortran respectively yields different interface of `zdotc_` and `zdotu_`.
bb93231673313764894fd17672fcda3

So the conclusion is that using `___MKL` to seperate two kinds of interfaces is unreasonable. That's why I rewrite this PR. 

We reached an agreement to implement customized "dotc" and "dotu" based on `sdot_` and `ddot_`.  I've put the formulas in the comments and added unittests with different 'incX' and 'incY'.
